Repository AY2021S1-CS2103T-W10-1/tp, pull requests merged in 2020-11, with the labels that each got.

#227 update ui
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ShowStatisticCommand.java
  src/main/java/seedu/address/logic/commands/SortByAmountCommand.java
  src/main/java/seedu/address/logic/commands/SortByTimeCommand.java
  src/main/java/seedu/address/model/ExpenseBook.java
  src/main/java/seedu/address/model/ReadOnlyExpenseBook.java
  src/main/java/seedu/address/model/expense/CommandList.java
  src/main/java/seedu/address/ui/BudgetPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PieChartWindow.java
  src/main/java/seedu/address/ui/StatisticTable.java
  src/main/resources/view/BudgetPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ExpenseListCard.fxml
  src/main/resources/view/HelpCommandWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/model/ExpenseBookTest.java
Labels: type.Enhancement

#233 Modify the add command + Add in Edit Command + edit user guide
  docs/UserGuide.md
  docs/images/EditCommand.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddExpenseCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ExpenseBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/expense/Amount.java
  src/main/java/seedu/address/model/expense/Category.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: priority.Medium, type.Enhancement

#237 Code quality improvement
  docs/UserGuide.md
  docs/images/CurrencyCodes.png
  docs/images/EditCommand.png
  docs/images/ExchangeCommand-after.png
  docs/images/ExchangeRates.png
  docs/images/Ui.png
  docs/images/addExpenseCommand.png
  docs/images/deleteExpenseCommand.png
  docs/images/listByCategoryCommand.png
  docs/images/listByDateCommand.png
  docs/images/listByDescCommand.png
  docs/images/listCommand.png
  docs/images/setBudgetCommand.png
  docs/images/showStatisticCommand.png
  docs/images/showStatisticTable.png
  docs/images/sortByAmount%20ascending.png
  docs/images/sortByAmount.png
  docs/images/viewCategoryCommand.png
  docs/images/viewCommand.png
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CurrenciesCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExchangeCommand.java
  src/main/java/seedu/address/logic/commands/ListExpenseByCategoryCommand.java
  src/main/java/seedu/address/logic/commands/ListExpenseByDateCommand.java
  src/main/java/seedu/address/logic/commands/ListExpenseByDescCommand.java
  src/main/java/seedu/address/logic/commands/RatesCommand.java
  src/main/java/seedu/address/logic/commands/SetBudgetCommand.java
  src/main/java/seedu/address/logic/commands/ShowStatisticCommand.java
  src/main/java/seedu/address/logic/commands/SortByAmountCommand.java
  src/main/java/seedu/address/logic/commands/ViewCategoryCommand.java
  src/main/java/seedu/address/logic/parser/AddExpenseCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CurrenciesCommandParser.java
  src/main/java/seedu/address/logic/parser/ExpenseBookParser.java
  src/main/java/seedu/address/logic/parser/ListExpenseByCategoryCommandParser.java
  src/main/java/seedu/address/logic/parser/ListExpenseByDateCommandParser.java
  src/main/java/seedu/address/logic/parser/ListExpenseByDescCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RatesCommandParser.java
  src/main/java/seedu/address/model/ExpenseBook.java
  src/main/java/seedu/address/model/ExpenseModelManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ReadOnlyExpenseBook.java
  src/main/java/seedu/address/ui/BudgetPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/ExpenseBookTest.java
Labels: priority.Medium

#235 Branch add more test
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ShowStatisticCommand.java
  src/main/java/seedu/address/logic/commands/SortShowStatisticCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/expense/ExpenseList.java
  src/main/java/seedu/address/ui/HelpCommandWindow.java
  src/main/java/seedu/address/ui/StatisticTable.java
  src/test/java/seedu/address/logic/commands/AddExpenseCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/expense/AmountTest.java
  src/test/java/seedu/address/model/expense/StatisticSummaryTest.java
  src/test/java/seedu/address/testutil/EditExpenseDescriptorBuilder.java
Labels: priority.Medium, type.Task

#244 Add PPP and solve listbydate issue
  docs/DeveloperGuide.md
  docs/team/tanwayne890.md
  src/main/java/seedu/address/logic/commands/ListExpenseByDateCommand.java
  src/main/java/seedu/address/logic/parser/ListExpenseByDateCommandParser.java
Labels: severity.Medium

#246 RepoSense Compatible + modify help table
  docs/AboutUs.md
  docs/images/BILLXYR.png
  docs/team/billxyr.md
  src/main/java/seedu/address/model/expense/CommandList.java
  src/main/java/seedu/address/ui/HelpCommandWindow.java
  src/test/java/seedu/address/logic/commands/DeleteDescriptionCommandTest.java
  src/test/java/seedu/address/logic/commands/ListExpenseCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteDescriptionCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteExpenseCommandParserTest.java
Labels: type.Enhancement
