Repository AY2021S1-CS2103T-W10-1/tp, pull requests merged in 2020-10, with the labels that each got.

#50 Clean up DG format
  docs/DeveloperGuide.md
Labels: documentation

#56 Add expense.Description
  src/main/java/seedu/address/model/person/Description.java
  src/test/java/seedu/address/model/person/DescriptionTest.java
Labels: priority.High, type.Task

#54 Add expense.Category
  src/main/java/seedu/address/model/person/Category.java
  src/test/java/seedu/address/model/person/CategoryTest.java
Labels: priority.High, type.Task

#59 Add expense.Amount
  src/main/java/seedu/address/model/person/Amount.java
  src/test/java/seedu/address/model/person/AmountTest.java
Labels: priority.High, type.Task

#52 Add expense.Date
  src/main/java/seedu/address/model/person/Date.java
  src/test/java/seedu/address/model/person/DateTest.java
Labels: priority.High, type.Task

#61 Add expense.expense
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Description.java
  src/main/java/seedu/address/model/person/Expense.java
  src/test/java/seedu/address/model/person/ExpenseTest.java
  src/test/java/seedu/address/testutil/ExpenseBuilder.java
  src/test/java/seedu/address/testutil/TypicalExpense.java
Labels: priority.High, type.Task

#79 Add showBudget and setBudget commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SetBudgetCommand.java
  src/main/java/seedu/address/logic/commands/ShowBudgetCommand.java
  src/main/java/seedu/address/logic/parser/ExpenseBookParser.java
  src/main/java/seedu/address/logic/parser/SetBudgetCommandParser.java
  src/main/java/seedu/address/logic/parser/ShowBudgetCommandParser.java
  src/main/java/seedu/address/model/ExpenseBook.java
  src/main/java/seedu/address/model/ExpenseModelManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Amount.java
  src/main/java/seedu/address/model/person/UniqueExpenseList.java
Labels: priority.High

#72 Add the addExpense Command
  src/main/java/seedu/address/ExpenseMainApp.java
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddExpenseCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DescriptionCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddExpenseCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DescriptionCommandParser.java
  src/main/java/seedu/address/logic/parser/ExpenseBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/person/Description.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateExpenseException.java
  src/main/java/seedu/address/model/person/exceptions/ExpenseNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedExpense.java
  src/main/java/seedu/address/storage/JsonSerializableExpenseBook.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/ExpenseCard.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High, type.Task

#78 Branch add functionality add delete command function
  src/main/java/seedu/address/logic/commands/DeleteExpenseCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/DeleteExpenseCommandParser.java
  src/main/java/seedu/address/logic/parser/ExpenseBookParser.java
  src/main/java/seedu/address/model/ExpenseModelManager.java
Labels: priority.High, type.Task

#80 Fix nits in conflicts
  src/main/java/seedu/address/logic/commands/SetBudgetCommand.java
  src/main/java/seedu/address/logic/commands/ShowBudgetCommand.java
  src/main/java/seedu/address/logic/parser/ExpenseBookParser.java
Labels: priority.Medium

#70 Add view command and parser
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ViewCategoryCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/ExpenseBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCategoryCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/ExpenseBook.java
  src/main/java/seedu/address/model/ExpenseModelManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Expense.java
  src/main/java/seedu/address/model/person/UniqueExpenseList.java
Labels: priority.High

#83 Add view category command
  src/main/java/seedu/address/ExpenseMainApp.java
  src/main/java/seedu/address/logic/commands/DeleteDescriptionCommand.java
  src/main/java/seedu/address/logic/commands/ViewCategoryCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/ExpenseBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCategoryCommandParser.java
  src/main/java/seedu/address/model/ExpenseBook.java
  src/main/java/seedu/address/model/ExpenseModelManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Expense.java
  src/main/java/seedu/address/model/person/UniqueExpenseList.java
Labels: priority.High, type.Task

#93 Modify checkstyle
  src/main/java/seedu/address/logic/parser/ExpenseBookParser.java
  src/test/java/seedu/address/model/person/DescriptionTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.High, severity.High, type.Bug

#94 Add ExpenseTest
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/parser/DeleteExpenseCommandParser.java
  src/test/java/seedu/address/model/person/DescriptionTest.java
  src/test/java/seedu/address/model/person/ExpenseTest.java
Labels: type.Task

#106 Branch add AddExpenseTest and Assertions
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddExpenseCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ExpenseBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/person/Category.java
  src/main/java/seedu/address/model/person/Date.java
  src/test/java/seedu/address/logic/commands/AddExpenseCommandTest.java
  src/test/java/seedu/address/model/person/CategoryTest.java
  src/test/java/seedu/address/testutil/ExpenseBuilder.java
Labels: priority.High, type.Task

#101 Modify the Common Package and corresponding command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ExpenseBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
Labels: priority.High, type.Task

#110 Fix checkstyle
  src/test/java/seedu/address/commons/util/JsonUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddExpenseCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ListExpenseCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/person/ExpenseTest.java
  src/test/java/seedu/address/storage/JsonAdaptedExpenseTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#115 Update the DG with design details
  docs/DeveloperGuide.md
  docs/diagrams/deleteExpenseSequenceDiagram.puml
  docs/diagrams/deleteState0.puml
  docs/diagrams/deleteState1.puml
  docs/diagrams/deleteState2.puml
  docs/diagrams/deleteState3.puml
  docs/diagrams/deleteState4.puml
  docs/images/deleteExpenseSequenceDiagram.png
  docs/images/deleteState0.png
  docs/images/deleteState1.png
  docs/images/deleteState2.png
  docs/images/deleteState3.png
Labels: priority.High, type.Task

#116 Fix check style error
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/parser/ExpenseBookParser.java
Labels: severity.Medium, type.Bug

#118 Add more tests
  src/main/java/seedu/address/logic/parser/ExpenseBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddExpenseCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/ExpenseBookParserTest.java
Labels: priority.Medium, type.Task

#119 Add in more test
  src/main/java/seedu/address/model/expense/Amount.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddExpenseCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddExpenseCommandParserTest.java
Labels: priority.High, type.Task

#121 Modify the Test and Fix the CI pass
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddExpenseCommandParserTest.java
Labels: severity.High, type.Bug, type.Enhancement

#124 Add back DG images
  docs/images/deleteState0.png
  docs/images/deleteState1.png
  docs/images/deleteState2.png
  docs/images/deleteState3.png
Labels: priority.High, type.Bug

#125 Modify some typo
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: severity.Low, type.Bug

#126 Add in the ShowStatisticCommand
  src/main/java/seedu/address/logic/commands/ShowStatisticCommand.java
  src/main/java/seedu/address/logic/parser/ExpenseBookParser.java
  src/main/java/seedu/address/logic/parser/ShowStatisticCommandParser.java
  src/main/java/seedu/address/model/ExpenseBook.java
  src/main/java/seedu/address/model/ExpenseModelManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/expense/UniqueExpenseList.java
Labels: priority.High, type.Task

#134 Update DG and fix logic errors in model package
  docs/DeveloperGuide.md
  docs/diagrams/ExpenseClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ShowBudgetActivityDiagram.puml
  docs/diagrams/ShowBudgetSequenceDiagram.puml
  docs/images/ExpenseClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ShowBudgetActivityDiagram.png
  docs/images/ShowBudgetSequenceDiagram.png
  docs/images/UndoRedoState1.png
  docs/team/yuanxing.md
  src/main/java/seedu/address/logic/parser/ShowStatisticCommandParser.java
  src/main/java/seedu/address/model/ExpenseBook.java
  src/main/java/seedu/address/model/expense/Expense.java
  src/main/java/seedu/address/model/expense/ExpenseList.java
  src/main/java/seedu/address/model/expense/exceptions/DuplicateExpenseException.java
Labels: priority.High

#141 Exchange currency command
  src/main/java/seedu/address/logic/commands/AddExpenseCommand.java
  src/main/java/seedu/address/logic/commands/ExchangeCommand.java
  src/main/java/seedu/address/logic/commands/SetBudgetCommand.java
  src/main/java/seedu/address/logic/commands/ShowBudgetCommand.java
  src/main/java/seedu/address/logic/commands/ShowStatisticCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ExchangeCommandParser.java
  src/main/java/seedu/address/logic/parser/ExpenseBookParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ShowBudgetCommandParser.java
  src/main/java/seedu/address/model/ExpenseBook.java
  src/main/java/seedu/address/model/ExpenseModelManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/expense/Amount.java
  src/main/java/seedu/address/model/expense/Expense.java
  src/main/java/seedu/address/model/expense/ExpenseList.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High

#142 Create more classes to follow OOP, Change UI to support currency exchange
  src/main/java/seedu/address/logic/commands/.gradle/6.6.1/fileChanges/last-build.bin
  src/main/java/seedu/address/logic/commands/.gradle/6.6.1/fileHashes/fileHashes.lock
  src/main/java/seedu/address/logic/commands/.gradle/6.6.1/gc.properties
  src/main/java/seedu/address/logic/commands/.gradle/checksums/checksums.lock
  src/main/java/seedu/address/logic/commands/.gradle/configuration-cache/gc.properties
  src/main/java/seedu/address/logic/commands/.gradle/vcs-1/gc.properties
  src/main/java/seedu/address/logic/commands/ExchangeCommand.java
  src/main/java/seedu/address/logic/commands/SetBudgetCommand.java
  src/main/java/seedu/address/logic/commands/ShowBudgetCommand.java
  src/main/java/seedu/address/logic/parser/ExchangeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetBudgetCommandParser.java
  src/main/java/seedu/address/model/ExpenseBook.java
  src/main/java/seedu/address/model/ExpenseModelManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/expense/Amount.java
  src/main/java/seedu/address/model/expense/Budget.java
  src/main/java/seedu/address/model/expense/Currency.java
  src/main/java/seedu/address/model/expense/ExchangeRate.java
  src/main/java/seedu/address/model/expense/Expense.java
  src/main/java/seedu/address/model/expense/ExpenseList.java
  src/main/java/seedu/address/ui/ExpenseCard.java
Labels: priority.High, type.Enhancement

#147 Branch add functionality sort show statistic command
  src/main/java/seedu/address/logic/commands/ShowStatisticCommand.java
  src/main/java/seedu/address/logic/commands/SortShowStatisticCommand.java
  src/main/java/seedu/address/model/ExpenseBook.java
  src/main/java/seedu/address/model/ExpenseModelManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/expense/ExpenseList.java
Labels: priority.High, type.Enhancement

#152 Fix flaws in budget commands
  src/main/java/seedu/address/logic/commands/AddExpenseCommand.java
  src/main/java/seedu/address/logic/commands/ExchangeCommand.java
  src/main/java/seedu/address/logic/commands/ShowBudgetCommand.java
  src/main/java/seedu/address/logic/parser/AddExpenseCommandParser.java
  src/main/java/seedu/address/model/ExpenseBook.java
  src/main/java/seedu/address/model/expense/Budget.java
Labels: type.Bug

#153 Update small bug in User Guide
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: priority.Medium, type.Bug, type.Enhancement

#155 Add in more test
  src/main/java/seedu/address/logic/commands/ListExpenseByCategoryCommand.java
  src/main/java/seedu/address/logic/commands/ListExpenseByDateCommand.java
  src/main/java/seedu/address/logic/commands/ListExpenseByDescCommand.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteDescriptionCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListExpenseCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteDescriptionCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteExpenseCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalExpenses.java
Labels: priority.High, type.Task

#171 Update the JavaDoc2
  src/main/java/seedu/address/logic/commands/AddDescriptionCommand.java
  src/main/java/seedu/address/logic/commands/AddExpenseCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteDescriptionCommand.java
  src/main/java/seedu/address/logic/commands/DeleteExpenseCommand.java
  src/main/java/seedu/address/logic/commands/ExchangeCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListExpenseByCategoryCommand.java
  src/main/java/seedu/address/logic/commands/ListExpenseByDateCommand.java
  src/main/java/seedu/address/logic/commands/ListExpenseByDescCommand.java
  src/main/java/seedu/address/logic/commands/ListExpenseCommand.java
  src/main/java/seedu/address/logic/commands/SetBudgetCommand.java
  src/main/java/seedu/address/logic/commands/ShowBudgetCommand.java
  src/main/java/seedu/address/logic/commands/ShowStatisticCommand.java
  src/main/java/seedu/address/logic/commands/SortByAmountCommand.java
  src/main/java/seedu/address/logic/commands/SortByTimeCommand.java
  src/main/java/seedu/address/logic/commands/ViewCategoryCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/java/seedu/address/logic/parser/ExchangeCommandParser.java
  src/main/java/seedu/address/logic/parser/ExitCommandParser.java
  src/main/java/seedu/address/logic/parser/ExpenseBookParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/SetBudgetCommandParser.java
  src/main/java/seedu/address/logic/parser/ShowBudgetCommandParser.java
  src/main/java/seedu/address/logic/parser/ShowStatisticCommandParser.java
  src/main/java/seedu/address/logic/parser/SortByAmountCommandParser.java
  src/main/java/seedu/address/logic/parser/SortByTimeCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCategoryCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/expense/Amount.java
  src/main/java/seedu/address/model/expense/Budget.java
  src/main/java/seedu/address/model/expense/Currency.java
  src/main/java/seedu/address/model/expense/CurrencyExchangeRate.java
  src/main/java/seedu/address/model/expense/Date.java
  src/main/java/seedu/address/model/expense/ExchangeRate.java
  src/main/java/seedu/address/model/expense/Expense.java
  src/main/java/seedu/address/model/expense/ExpenseList.java
  src/main/java/seedu/address/model/expense/Statistics.java
  src/test/java/seedu/address/logic/commands/AddDescriptionCommandTest.java
  src/test/java/seedu/address/logic/commands/AddExpenseCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteDescriptionCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ListExpenseCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewExpenseCommandTest.java
  src/test/java/seedu/address/testutil/ExpenseBookBuilder.java
  src/test/java/seedu/address/testutil/ExpenseBuilder.java
  src/test/java/seedu/address/testutil/TypicalExpenses.java
Labels: priority.High, type.Task

#172 Exchange without entering exchange rate
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ExchangeCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ExchangeCommandParser.java
  src/main/java/seedu/address/model/expense/Budget.java
  src/main/java/seedu/address/model/expense/Currency.java
  src/main/java/seedu/address/model/expense/CurrencyConverter.java
  src/main/java/seedu/address/model/expense/ExchangeRate.java
  src/main/java/seedu/address/storage/JsonAdaptedExpense.java
  src/main/java/seedu/address/storage/JsonSerializableExpenseBook.java
Labels: type.Enhancement

#175 Add supported currency table
  src/main/java/seedu/address/logic/commands/ExchangeCommand.java
  src/main/java/seedu/address/model/expense/CurrencyFullName.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PieChartWindow.java
  src/main/java/seedu/address/ui/SupportedCurrencyTable.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SupportedCurrencyTable.fxml
Labels: priority.Medium

#176 Make Exchange Table consistent
  src/main/java/seedu/address/ui/CurrencyExchangeTable.java
  src/main/resources/view/CurrencyExchangeTable.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium

#179 Add in the Statistic Table
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ShowStatisticCommand.java
  src/main/java/seedu/address/logic/commands/SortShowStatisticCommand.java
  src/main/java/seedu/address/model/ExpenseBook.java
  src/main/java/seedu/address/model/ReadOnlyExpenseBook.java
  src/main/java/seedu/address/model/expense/ExpenseList.java
  src/main/java/seedu/address/model/expense/StatisticSummary.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatisticTable.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatisticTable.fxml
Labels: priority.Medium, type.Task

#180 Fixed CI failure
  src/main/java/seedu/address/model/ExpenseBook.java
  src/main/java/seedu/address/model/ReadOnlyExpenseBook.java
  src/main/java/seedu/address/model/expense/Statistics.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatisticTable.java
  src/main/resources/view/StatisticTable.fxml
  src/test/java/seedu/address/model/ExpenseBookTest.java
Labels: severity.High

#225 Modify window size and other bugs
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/helpCommandWindow.png
  src/main/java/seedu/address/logic/commands/ListExpenseByCategoryCommand.java
  src/main/java/seedu/address/logic/commands/ListExpenseByDateCommand.java
  src/main/java/seedu/address/logic/commands/ListExpenseByDescCommand.java
  src/main/java/seedu/address/logic/parser/ListExpenseByDateCommandParser.java
  src/main/java/seedu/address/logic/parser/SortByTimeCommandParser.java
  src/main/java/seedu/address/model/expense/Amount.java
  src/main/java/seedu/address/model/expense/CommandList.java
  src/main/java/seedu/address/model/expense/Date.java
  src/main/java/seedu/address/ui/HelpCommandWindow.java
  src/main/java/seedu/address/ui/StatisticTable.java
  src/test/java/seedu/address/model/expense/AmountTest.java
  src/test/java/seedu/address/model/expense/DateTest.java
Labels: priority.Medium, type.Enhancement

#226 Fix amount parsing error
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/expense/Amount.java
Labels: priority.High, type.Bug
